### ISSUE TITLE
add cli sanitizer options

### ISSUE THREAD

**Issue by PhilipDeegan** [PhilipDeegan/maiken#72]

**Comment by PhilipDeegan** [comment]
resolvable via specific settings yaml file like 

```

property:
  cxx_flags: -std=c++20 -fsanitize=address -fno-omit-frame-pointer
local:
  repo: /mkn/r
  mod-repo: /mkn/m

remote:
  repo: git@github.com:mkn/
  mod-repo: git@github.com:mkn-mod/

path: |
  /usr/lib/clang/18/lib/x86_64-redhat-linux-gnu

# replace with $(clang++ -print-file-name=libclang_rt.asan-x86_64.so)
env: | 
  MKN_LD_PRELOAD=/usr/lib/clang/18/lib/x86_64-redhat-linux-gnu/libclang_rt.asan.so
  ASAN_OPTIONS=detect_leaks=0

file:
  - type: cpp:cxx:cc:c:S
    archiver: ar -cr
    compiler: clang++ ${cxx_flags}
    linker: clang++ -lclang_rt.asan-x86_64

```
